name: Publish to NPM
on:
  release:
    types:
      - released
      - prereleased
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: 21

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Publish
        run: pnpm publish --tag latest
